[DEFAULT]
width        = 400
height       = 600
using_IDLE   = True
colormode    = 255

# bgcolor      = lightblue
pen_color    = red
# pen_size     = 5

# square_x     = 0
# square_y     = 0
# square_len   = 100
